"""user

Revision ID: 469b1d948144
Revises: 388ebe35cc7b
Create Date: 2025-03-21 15:31:24.820893

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '469b1d948144'
down_revision: Union[str, None] = '388ebe35cc7b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('summaries', sa.Column('main_idea', sa.Text(), nullable=True))
    op.add_column('summaries', sa.Column('key_points', sa.Text(), nullable=True))
    op.add_column('summaries', sa.Column('conclusion', sa.Text(), nullable=True))
    op.alter_column('summaries', 'text',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('summaries', 'summary',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('summaries', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_index('ix_summaries_id', table_name='summaries')
    op.drop_constraint('summaries_user_id_fkey', 'summaries', type_='foreignkey')
    op.create_foreign_key(None, 'summaries', 'users', ['user_id'], ['id'])
    op.drop_column('summaries', 'created_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('summaries', sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'summaries', type_='foreignkey')
    op.create_foreign_key('summaries_user_id_fkey', 'summaries', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_index('ix_summaries_id', 'summaries', ['id'], unique=False)
    op.alter_column('summaries', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('summaries', 'summary',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('summaries', 'text',
               existing_type=sa.TEXT(),
               nullable=False)
    op.drop_column('summaries', 'conclusion')
    op.drop_column('summaries', 'key_points')
    op.drop_column('summaries', 'main_idea')
    # ### end Alembic commands ###
