"""sonvurus

Revision ID: b0f37ab7be3c
Revises: 05cb10657906
Create Date: 2025-03-21 16:13:03.306902

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b0f37ab7be3c'
down_revision: Union[str, None] = '05cb10657906'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('summaries', sa.Column('format', sa.String(), nullable=True))
    op.alter_column('summaries', 'text',
               existing_type=sa.TEXT(),
               nullable=False)
    op.create_index(op.f('ix_summaries_id'), 'summaries', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_summaries_id'), table_name='summaries')
    op.alter_column('summaries', 'text',
               existing_type=sa.TEXT(),
               nullable=True)
    op.drop_column('summaries', 'format')
    # ### end Alembic commands ###
